name = "nongor-reports"
main = "src/index.py"
compatibility_date = "2024-03-31"
compatibility_flags = ["python_workers"]

[triggers]
crons = ["0 21 * * *"]

[vars]
# The following must be set via `wrangler secret put`:
# TELEGRAM_BOT_TOKEN
# DATABASE_URL
# ADMIN_USER_IDS
